version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "meteor",
    "vue",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "mocha",
    "browser"
  ]